config/routes.rb
Rails.application.routes.draw do
  

mount CuteV1::GrapeAPI => '/v1'

get "product/:id/sold" => 'products#sold'
 

namespace :dashboard do
  resources :orders, :only => [:index, :update]
end

  devise_for :managers
  devise_for :users
  resources :statics, :only => [:index]

  resources :items, :only =>[:index, :show] do
    member do 
      get :add_cart    
    end
  end

  namespace :dashboard do 
    resources :orders

    namespace :admin do 
      resources :items
      resources :cates
      resources :orders
      resources :users
      resources :managers
    end
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/cate.rb
class Cate < ActiveRecord::Base	
  has_many :items
end

app/models/dashboard/admin.rb
module Dashboard::Admin
  def self.table_name_prefix
    'dashboard_admin_'
  end
end

app/models/dashboard/admin/item.rb
class Dashboard::Admin::Item < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
	
  belongs_to :cate
  
  has_attached_file :cover,
   styles:{
   original:"1024*1024>",
   cover: "300x300>", 
   icon: "100x100#" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable #:registerable,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base	
 has_many :order_items
end

app/models/order_item .rb
class OrderItem < ActiveRecord::Base	
  belongs_to :item
  belongs_to :user
  belongs_to :order
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base	
  belongs_to :item
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #has_many :order_items
  #如果沒用到的就直接關掉
  devise :database_authenticatable, :registerable
         #:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # include SimpleCaptcha::ControllerHelpers
end

app/controllers/dashboard/admin/admin_controller.rb
class Dashboard::Admin::AdminController < ApplicationController
	before_action :authenticate_manager!
	layout 'admin'
end

app/controllers/dashboard/admin/items_controller.rb
class Dashboard::Admin::ItemsController < Dashboard::Admin::AdminController 
  before_action :set_dashboard_admin_item, only: [:show, :edit, :update, :destroy]

  # GET /dashboard/admin/items
  def index
    # id DESC 是說id 會從後面排回來,後台通常這樣,新產生的在前面
    @Items = @paginate = ::Item.order('id DESC').includes(:cate).paginate(:page => params[:page])
  end
  

  # GET /dashboard/admin/items/1
  def show
  end

  # GET /dashboard/admin/items/new
  def new
    #@dashboard_admin_item = Dashboard::Admin::Item.new
    @Items = ::Item.new(item_params)
  end

  # GET /dashboard/admin/items/1/edit
  def edit
    @item = ::Item.find(params[:id])
  end

  # POST /dashboard/admin/items
  def create
    @Items = ::Item.new(item_params)

    if @Items.save
      redirect_to @Items, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dashboard/admin/items/1
  def update
    @item = ::Item.find(params[:id])
    @item.update(item_params)
    redirect_to dashboard_admin_items_path
    
  end

  # DELETE /dashboard/admin/items/1
  def destroy
    @item.destroy
    redirect_to dashboard_admin_items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_admin_item
      @item = ::Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit!
    end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
	#驗證使用者
	before_action :authenticate_user!
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::DashboardController
	#繼承dashboard controller 
	#do CRUD

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController	
	def index
		@item = @paginate = Item.includes(:cate).paginate(:page => params[:page])
    	#@item = @paginate = Item.order('id DESC').includes(:cate).paginate(:page => params[:page])
	end

	def show
		@item = Item.find(params[:id])
	end

	def add_cart
		
		#hash
		session[:cart] ||={}
		item = Item.where(:id => params[:id]).first
		if item
			key = item.id.to_s
			session[:cart][key] ||=0
			session[:cart][key] +=1
		end

		render :json => {:counter => session[:cart].length}.to_json
		
	end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

def index
	#show all item
	#use will_paginate
	@item = @paginate = Item.paginate(:page => params[:page])
end



end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_cart_count
		if session[:cart]
			return session[:cart].length	
		else
			return 0	
		end
	end
end

app/helpers/dashboard/admin/admin_helper.rb
module Dashboard::Admin::AdminHelper
end

app/helpers/dashboard/admin/items_helper.rb
module Dashboard::Admin::ItemsHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/dashboard/admin/items/_form.html.erb
<%= form_for(@dashboard_admin_item) do |f| %>
  <% if @dashboard_admin_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard_admin_item.errors.count, "error") %> prohibited this dashboard_admin_item from being saved:</h2>

      <ul>
      <% @dashboard_admin_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/admin/items/edit.html.erb
<h1>Editing Dashboard Admin Item</h1>

<%#= render 'form' %>

<%= form_for(@item ,{:url => dashboard_admin_item_path, :method => 'patch'}) do |f| %>
名稱 <%= f.text_field :name %> <br>
價格 <%= f.number_field :price %> <br>
圖片	<%= f.file_field  :cover %> <br>
類別 <%= f.select :cate_id ,Cate.all.map{|c|[c.name,c.id]} %>
<button type = 'submit'>新增資料</button>
<% end %>



<%= link_to 'Show', @dashboard_admin_item %> |
<%= link_to 'Back', dashboard_admin_items_path %>

app/views/dashboard/admin/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dashboard Admin Items</h1>

<table>
  <thead> 
    
    <tr>
      <!-- <th colspan="3"></th> -->
      <th>id</th>
      <th>圖片</th>
      <th>類別</th>
      <th>名稱</th>
      <th>價格</th>
      <th>管理</th>
    </tr>
  </thead>

  <tbody>
    <% @Items.each do |i| %>
      <tr> 
        <th><%= i.id %></th>
        
        <th><%= image_tag(i.cover.url(:icon), size: "100x100", ) %></th>
        <th><%= i.cate.name %></th>
        
        <th><%= i.name %></th>
        <th><%= i.price %></th>
        <!-- <td><%#= link_to 'Show', dashboard_admin_item %></td> -->
        <td>
          <%= link_to 'Edit', edit_dashboard_admin_item_path(i) %>
          <%= link_to 'Destroy', dashboard_admin_item_path(i), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_dashboard_admin_item_path %>

app/views/dashboard/admin/items/new.html.erb
<h1>New Dashboard Admin Item</h1>

<%= form_for(@Item , dashboard_admin_items_path, :method => 'post') do |f| %>

名稱 <%= f.text_field :name %> <br>
價格 <%= f.number_field :price %> 
<button type = 'submit'>新增資料</button>
 
<% end %>


<%= link_to 'Back', dashboard_admin_items_path %>

app/views/dashboard/admin/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_admin_item_path(@dashboard_admin_item) %> |
<%= link_to 'Back', dashboard_admin_items_path %>

app/views/items/index.html.erb
<%#= form_for Item.new do |f| %>
  
  <%#= recaptcha_tags %>

<%# end %>


<!-- 執行 ajax加入購物車數量 -->





<% content_for :header do  %>
<script type="text/javascript">
  jQuery(function($) {
    // body...
    $('.add_cart').click(function(){
      $.getJSON('items/' +$(this).attr('data-value') +'/add_cart', function(json){
        $('#cart_counter').html(json.counter);
      });
      return false;
    });
  });
</script>
<% end %>


<h1>Hi 我是首頁</h1>

<table>
  <thead> 
    
    <tr>
      <!-- <th colspan="3"></th> -->
     
      <th>圖片</th>
      <th>類別</th>
      <th>名稱</th>
      <th>價格</th>
      <th>管理</th>
      
    </tr>
  </thead>

  <tbody>
    <% @item.each do |i| %>
      <tr> 
        
        
        <th><%= image_tag(i.cover.url(:icon), size: "100x100", ) %></th>
        <th><%= i.cate.name %></th>
        
        <th><%= i.name %></th>
        <th><%= i.price %></th>
        <th><a href="#" data-value = <%= i.id %> class="add_cart"> <i class="fa fa-cart-plus"></i>加入購物車</th> </a>
        <!-- <td><%#= link_to 'Show', dashboard_admin_item %></td> -->
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/index_backup.html.erb
<!-- 執行 ajax加入購物車數量 -->





<% content_for :header do  %>
<script type="text/javascript">
	jQuery(function($) {
		// body...
		$('.add_cart').click(function(){
			$.getJSON('items/' +$(this).attr('data-value') +'/add_cart', function(json){
				$('#cart_counter').html(json.counter);
			});
			return false;
		});
	});
</script>
<% end %>


<h1>Hi 我是首頁</h1>

<table>
  <thead> 
    
    <tr>
      <!-- <th colspan="3"></th> -->
     
      <th>圖片</th>
      <th>類別</th>
      <th>名稱</th>
      <th>價格</th>
      <th>管理</th>
      
    </tr>
  </thead>

  <tbody>
    <% @item.each do |i| %>
      <tr> 
        
        
        <th><%= image_tag(i.cover.url(:icon), size: "100x100", ) %></th>
        <th><%= i.cate.name %></th>
        
        <th><%= i.name %></th>
        <th><%= i.price %></th>
        <th><a href="#" data-value = <%= i.id %> class="add_cart"> <i class="fa fa-cart-plus"></i>加入購物車</th> </a>
        <!-- <td><%#= link_to 'Show', dashboard_admin_item %></td> -->
        
      </tr>
    <% end %>
  </tbody>
</table>