config/routes.rb
Rails.application.routes.draw do
  

mount CuteV1::GrapeAPI => '/v1'

get "product/:id/sold" => 'products#sold'
 

namespace :dashboard do
  resources :orders, :only => [:index, :update]
end

  devise_for :managers
  devise_for :users
  resources :statics, :only => [:index]

  resources :items, :only =>[:index, :show] do
    member do 
      get :add_cart    
    end
  end

  namespace :dashboard do 
    resources :orders

    namespace :admin do 
      resources :items
      resources :cates
      resources :orders
      resources :users
      resources :managers
    end
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/cate.rb
class Cate < ActiveRecord::Base	
  has_many :items
end

app/models/dashboard/admin.rb
module Dashboard::Admin
  def self.table_name_prefix
    'dashboard_admin_'
  end
end

app/models/dashboard/admin/item.rb
class Dashboard::Admin::Item < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
	
  belongs_to :cate
  
  has_attached_file :cover,
   styles:{
   original:"1024*1024>",
   cover: "300x300>", 
   icon: "100x100#" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable #:registerable,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base	
 has_many :order_items
end

app/models/order_item .rb
class OrderItem < ActiveRecord::Base	
  belongs_to :item
  belongs_to :user
  belongs_to :order
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base	
  belongs_to :item
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #has_many :order_items
  #如果沒用到的就直接關掉
  devise :database_authenticatable, :registerable
         #:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # include SimpleCaptcha::ControllerHelpers
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
	#驗證使用者
	before_action :authenticate_user!
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::DashboardController
	#繼承dashboard controller 
	#do CRUD

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController	
	def index
		@item = @paginate = Item.includes(:cate).paginate(:page => params[:page])
    	#@item = @paginate = Item.order('id DESC').includes(:cate).paginate(:page => params[:page])
	end

	def show
		@item = Item.find(params[:id])
	end

	def add_cart
		
		#hash
		session[:cart] ||={}
		item = Item.where(:id => params[:id]).first
		if item
			key = item.id.to_s
			session[:cart][key] ||=0
			session[:cart][key] +=1
		end

		render :json => {:counter => session[:cart].length}.to_json
		
	end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

def index
	#show all item
	#use will_paginate
	@item = @paginate = Item.paginate(:page => params[:page])
end



end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_cart_count
		if session[:cart]
			return session[:cart].length	
		else
			return 0	
		end
	end
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
<body>
	
	<h1>後台頁面 admin</h1>	

 <% if current_manager %>
<h1>Hi <%= current_manager.email %> </h1> 
<hr>
<%= link_to "log out", destroy_user_session_path, :method => 'delete' %>
 <% end %>

 <ul>  <%= link_to "商品管理", dashboard_admin_items_path %> </ul>
 

<%= will_paginate @paginate if @paginate %>
<hr>
<%= yield %>

<hr>

<%= will_paginate @paginate if @paginate %>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :header %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>

	<h1> 對外頁面:public</h1>
	
	<div>購物車數量：<span id = "cart_counter"><%= get_cart_count %> </span></div>
  <%= session[:cart] %> <br>


 <% if current_user %>


<h1>Hi <%= current_user.email %> </h1> 
<hr>
<%= link_to "log out", destroy_user_session_path, :method => 'delete' %>



 <% else %>

 <%= link_to "login", new_user_session_path %>
 <% end %>
 <%= link_to "register", new_user_registration_path %>

<%= will_paginate @paginate if @paginate %>
<hr>
<%= yield %>

<hr>

<%= will_paginate @paginate if @paginate %>



</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<h1>使用者管理</h1>

 <% if current_user %>
<h1>Hi <%= current_user.email %> </h1> 
<hr>
<%= link_to "log out", destroy_user_session_path, :method => 'delete' %>



 <% else %>

 <%= link_to "login", new_user_session_path %>
 <% end %>
 <%= link_to "register", new_user_registration_path %>

<%= will_paginate @paginate if @paginate %>
<hr>
<%= yield %>

<hr>

<%= will_paginate @paginate if @paginate %>



</body>
</html>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/css">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>

  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>

  <div class='simple_captcha_refresh_button'>
    <%= simple_captcha_options[:refresh_button] %>
  </div>
</div>